default: &default
  adapter: postgresql
  reconnect: false
  pool: 10
  username: ductoanle
  password:
  min_messages: WARNING

development: &development
  <<: *default
  database: googletv-hackathon

test: &test
  <<: *default
  database: googletv-hackathon-test

production:
  <<: *development

cucumber:
  <<: *test
